### ISSUE TITLE
[PE-D][Tester A] Details of Contacts not shown

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W13-4/tp#129]
Problem: The full details of the contacts are not shown. (shows `...`)

![image.png](https://raw.githubusercontent.com/LianGuoYang/ped/main/files/211c6f11-c122-49b1-bf44-72655201993b.png)

Suggestions: 
1. Increase the width of the window
2. Set max number of characters for each field
3. Add details at a new line

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LianGuoYang/ped#1

**Comment by Devanshshah1309** [comment]
Personally, I don't see this as a bug coz address isn't really important anyway - you can consider removing address altogether as internally discussed (since removing features is allowed in v1.4 if they result in bugs). If you remove address, remember to remove it from everywhere (`add person`, `edit person`, the UI, etc.)
