### ISSUE TITLE
Adding duplicate task and team throws exception instead of error message

### ISSUE THREAD

**Issue by ling-ui** [AY2223S1-CS2103T-W13-4/tp#195]
![image](https://user-images.githubusercontent.com/89027464/200042118-0f604949-4185-4521-b1a4-65169c900405.png)
A task with the same task name can be added as long as the deadlines are not the same -- this is ok if we plan to allow such behaviour

![image](https://user-images.githubusercontent.com/89027464/200042675-9171c452-1d30-41e1-8e83-457f99c19eaf.png)
But adding a task with the same task name, assignee and deadline throws an error instead of displaying an error message. Similar behavior for adding a team with the same team name as an existing team (try: "add team default" to reproduce).

**Comment by Devanshshah1309** [comment]
No - I don't think 2 tasks should have the same name even if the deadlines are different. We should be able to uniquely identify a task from the name itself. Otherwise, everytime you change deadline also you might have to check whether the "same" task exists.

Also, can you check whether we also need to fix the case when 2 tasks have different names and then we `edit task` for one of them to match the other?
